# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 671ca84ee20fd520128ce51c0eda6cc8a10038daac691e7199cac5ab16b548510a697eeb1d828036bad33c596b53c02fb8671317822e4ebc8929b503781800ea

test:
  secret_key_base: 4cfd3e3b465c5d0e5efbe8afe7137a4a4c65e248135f8265775471b442559c2f2cf2c5c4a61d60f6d68f00f7392c6e1ee3b29aae4e9fd5a82132d9ad8058d414

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
